# Generated by Django 3.0.8 on 2021-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicforumpost',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
