# Generated by Django 3.0.8 on 2021-09-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratting', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '4'), ('4', '4'), ('5', '5')], max_length=15, null=True)),
                ('Course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
