# Generated by Django 3.0.8 on 2021-09-05 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_ratting_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratting',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='ratting',
            new_name='rating',
        ),
    ]
