# Generated by Django 3.0.8 on 2021-09-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210905_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='Course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_pre', to='courses.Course'),
        ),
    ]
