# Generated by Django 3.0.8 on 2021-09-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210906_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
