# Generated by Django 3.0.8 on 2021-09-08 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='courses.Course')),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='enrolled_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
