# Generated by Django 3.0.8 on 2021-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20210908_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
