# Generated by Django 3.0.8 on 2021-09-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_test_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='Correct_Answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option_4',
        ),
        migrations.CreateModel(
            name='TestChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='courses.Test')),
            ],
        ),
    ]
