# Generated by Django 3.0.8 on 2021-09-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20210922_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testchoice',
            name='Course',
        ),
    ]
