# Generated by Django 3.0.8 on 2021-09-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_testchoice_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchoice',
            name='Lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_choice', to='courses.Lesson'),
        ),
    ]
