# Generated by Django 3.0.8 on 2021-09-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAboutBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('short_descripton', models.TextField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/site')),
                ('button_title', models.CharField(max_length=10)),
                ('button_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteHomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('short_descripton', models.TextField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/site')),
                ('button_title', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
