# Generated by Django 3.0.8 on 2021-09-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registerd',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
