# Generated by Django 3.0.8 on 2021-09-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0017_auto_20210908_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('enrolled_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseEnrollment')),
            ],
        ),
    ]
